/** Сквозные идентификаторы UI для спецификации, Storybook, реализации и e2e. */
export enum UIElements {
  APP_HEADER = 'app-header',
  APP_LOGO_LINK = 'app-logo-link',
  PUBLIC_BOOK_NAV_LINK = 'public-book-nav-link',
  ADMIN_NAV_LINK = 'admin-nav-link',

  HOME_SCREEN = 'home-screen',
  HOME_BOOK_BUTTON = 'home-book-button',
  HOME_FEATURES_PANEL = 'home-features-panel',

  CATALOG_SCREEN = 'catalog-screen',
  CATALOG_HEADING = 'catalog-heading',
  CATALOG_MEETING_TYPE_LIST = 'catalog-meeting-type-list',
  CATALOG_MEETING_TYPE_CARD = 'catalog-meeting-type-card',
  CATALOG_LOADING = 'catalog-loading',
  CATALOG_EMPTY_STATE = 'catalog-empty-state',
  CATALOG_ERROR_ALERT = 'catalog-error-alert',
  CATALOG_RETRY_BUTTON = 'catalog-retry-button',

  BOOKING_SCREEN = 'booking-screen',
  BOOKING_SUMMARY = 'booking-summary',
  BOOKING_DATE_CALENDAR = 'booking-date-calendar',
  BOOKING_TIMEZONE_LABEL = 'booking-timezone-label',
  BOOKING_SLOT_LIST = 'booking-slot-list',
  BOOKING_SLOT_BUTTON = 'booking-slot-button',
  BOOKING_NO_SLOTS_STATE = 'booking-no-slots-state',
  BOOKING_BACK_BUTTON = 'booking-back-button',
  BOOKING_CONTINUE_BUTTON = 'booking-continue-button',
  BOOKING_CONFLICT_ALERT = 'booking-conflict-alert',

  GUEST_DETAILS_SCREEN = 'guest-details-screen',
  GUEST_NAME_INPUT = 'guest-name-input',
  GUEST_EMAIL_INPUT = 'guest-email-input',
  GUEST_NOTE_INPUT = 'guest-note-input',
  GUEST_BACK_BUTTON = 'guest-back-button',
  GUEST_SUBMIT_BUTTON = 'guest-submit-button',
  GUEST_FORM_ERROR_ALERT = 'guest-form-error-alert',
  GUEST_SUBMIT_ERROR_ALERT = 'guest-submit-error-alert',
  GUEST_RETRY_BUTTON = 'guest-retry-button',

  BOOKING_SUCCESS_SCREEN = 'booking-success-screen',
  BOOKING_SUCCESS_DETAILS = 'booking-success-details',
  SUCCESS_BOOK_AGAIN_BUTTON = 'success-book-again-button',
  SUCCESS_HOME_LINK = 'success-home-link',

  ADMIN_SHELL = 'admin-shell',
  ADMIN_MEETING_TYPES_TAB = 'admin-meeting-types-tab',
  ADMIN_BOOKINGS_TAB = 'admin-bookings-tab',
  ADMIN_MEETING_TYPES_SCREEN = 'admin-meeting-types-screen',
  ADMIN_MEETING_TYPES_LIST = 'admin-meeting-types-list',
  ADMIN_MEETING_TYPE_CARD = 'admin-meeting-type-card',
  ADMIN_MEETING_TYPES_EMPTY_STATE = 'admin-meeting-types-empty-state',
  ADMIN_CREATE_MEETING_TYPE_BUTTON = 'admin-create-meeting-type-button',

  ADMIN_CREATE_MEETING_TYPE_SCREEN = 'admin-create-meeting-type-screen',
  ADMIN_MEETING_TYPE_ID_INPUT = 'admin-meeting-type-id-input',
  ADMIN_MEETING_TYPE_TITLE_INPUT = 'admin-meeting-type-title-input',
  ADMIN_MEETING_TYPE_DESCRIPTION_INPUT = 'admin-meeting-type-description-input',
  ADMIN_MEETING_TYPE_DURATION_SELECT = 'admin-meeting-type-duration-select',
  ADMIN_MEETING_TYPE_CANCEL_BUTTON = 'admin-meeting-type-cancel-button',
  ADMIN_MEETING_TYPE_SUBMIT_BUTTON = 'admin-meeting-type-submit-button',
  ADMIN_MEETING_TYPE_FORM_ERROR_ALERT = 'admin-meeting-type-form-error-alert',
  ADMIN_MEETING_TYPE_DUPLICATE_ALERT = 'admin-meeting-type-duplicate-alert',
  ADMIN_MEETING_TYPE_CREATED_NOTIFICATION = 'admin-meeting-type-created-notification',

  ADMIN_BOOKINGS_SCREEN = 'admin-bookings-screen',
  ADMIN_BOOKINGS_LIST = 'admin-bookings-list',
  ADMIN_BOOKING_CARD = 'admin-booking-card',
  ADMIN_BOOKINGS_EMPTY_STATE = 'admin-bookings-empty-state',
}
